nelmio_api_doc:
    documentation:
        info:
            title: F1monkey EVE characters
            description: Characters management microservice
            version: v1.0
    areas:
        default:
            path_patterns:
                - ^/
        v1:
            path_patterns:
                - ^/v1/