imports:
    - { resource: services/doctrine.yaml }
    - { resource: services/events.yaml }
    - { resource: services/log.yaml }

parameters:
    app.auth_code.max_per_user: 5
    app.auth_code.lifetime: 900
    app.email.from: '%env(EMAIL_FROM)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,EventListener,Entity,Exception,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']