parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    test.access_token_service:
        alias: App\Service\Character\AccessTokenServiceInterface